name: Build and deploy JAR app to Azure Web App

env:
  JAVA_VERSION: '17'

on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - bugfix/*
      - hotfix/*
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: gradle clean build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/build/libs/*-all.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Deploy to Azure Web App (production)
        if: github.ref == 'refs/heads/master'
        id: deploy-to-webapp-production
        uses: azure/webapps-deploy@v2
        with:
          app-name: prod-lectureapp
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*-all.jar'

      - name: Deploy to Azure Web App (develop)
        if: github.ref == 'refs/heads/develop'
        id: deploy-to-webapp-develop
        uses: azure/webapps-deploy@v2
        with:
          app-name: dev-lectureapp
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*-all.jar'

      - name: Deploy to Azure Web App (feature branches)
        if: startsWith(github.ref, 'refs/heads/feature/')
        id: deploy-to-webapp-feature
        uses: azure/webapps-deploy@v2
        with:
          app-name: feature-lectureapp
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*-all.jar'

      - name: Deploy to Azure Web App (bugfix branches)
        if: startsWith(github.ref, 'refs/heads/bugfix/')
        id: deploy-to-webapp-bugfix
        uses: azure/webapps-deploy@v2
        with:
          app-name: bugfix-lectureapp
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*-all.jar'

      - name: Deploy to Azure Web App (hotfix branches)
        if: startsWith(github.ref, 'refs/heads/hotfix/')
        id: deploy-to-webapp-hotfix
        uses: azure/webapps-deploy@v2
        with:
          app-name: hotfix-lectureapp
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*-all.jar'

      - name: Deploy to Azure Web App (release branches)
        if: startsWith(github.ref, 'refs/heads/release/')
        id: deploy-to-webapp-release
        uses: azure/webapps-deploy@v2
        with:
          app-name: release-lectureapp
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*-all.jar'
